-- ============================================================
-- Ledger — reference database schema (MySQL 8)
-- ============================================================
-- This schema DOCUMENTS the relational model behind the app's
-- mock data layer (src/data/seedData.js + src/services/mockDatabase.js).
-- The demo app does NOT require MySQL: all data lives in the browser
-- (in-memory, persisted to localStorage). This file exists so that:
--   1. The "Basic Database Schema" deliverable is satisfied.
--   2. A future real backend can adopt it without redesign.
--
-- Field mapping vs. the mock layer:
--   - mock `availableBalance` / `pendingHoldsTotal` are DERIVED here,
--     not stored: available = ledger_balance - SUM(pending debit holds).
--   - mock `transferGroupId` is normalized into the `transfers` table,
--     referenced by `transactions.transfer_id`.
-- ============================================================

CREATE TABLE customers (
  id          VARCHAR(36)  NOT NULL,
  name        VARCHAR(120) NOT NULL,
  email       VARCHAR(255) NOT NULL,
  created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_customers_email (email)
) ENGINE=InnoDB;

CREATE TABLE accounts (
  id              VARCHAR(36)   NOT NULL,
  customer_id     VARCHAR(36)   NOT NULL,
  account_number  CHAR(10)      NOT NULL,
  nickname        VARCHAR(80)   NOT NULL,
  type            ENUM('checking','savings') NOT NULL,
  status          ENUM('active','frozen','closed') NOT NULL DEFAULT 'active',
  currency        CHAR(3)       NOT NULL DEFAULT 'USD',
  -- Ledger balance only. Available balance is derived:
  --   available = ledger_balance
  --             - COALESCE(SUM(ABS(amount)) of pending debits, 0)
  ledger_balance  DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_accounts_number (account_number),
  KEY idx_accounts_customer (customer_id),
  CONSTRAINT fk_accounts_customer
    FOREIGN KEY (customer_id) REFERENCES customers (id)
) ENGINE=InnoDB;

-- One row per internal transfer between two accounts owned by the
-- same customer. Each successful transfer also inserts exactly two
-- rows into `transactions` (one debit, one credit) referencing it.
CREATE TABLE transfers (
  id               VARCHAR(36)   NOT NULL,
  from_account_id  VARCHAR(36)   NOT NULL,
  to_account_id    VARCHAR(36)   NOT NULL,
  amount           DECIMAL(12,2) NOT NULL,
  note             VARCHAR(255)  NULL,
  created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_transfers_from (from_account_id),
  KEY idx_transfers_to (to_account_id),
  CONSTRAINT fk_transfers_from
    FOREIGN KEY (from_account_id) REFERENCES accounts (id),
  CONSTRAINT fk_transfers_to
    FOREIGN KEY (to_account_id) REFERENCES accounts (id),
  CONSTRAINT ck_transfers_amount_positive
    CHECK (amount > 0),
  CONSTRAINT ck_transfers_distinct_accounts
    CHECK (from_account_id <> to_account_id)
) ENGINE=InnoDB;

CREATE TABLE transactions (
  id             VARCHAR(36)   NOT NULL,
  account_id     VARCHAR(36)   NOT NULL,
  -- NULL for ordinary card/payroll activity; set for the debit/credit
  -- pair generated by an internal transfer.
  transfer_id    VARCHAR(36)   NULL,
  date           TIMESTAMP     NOT NULL,
  description    VARCHAR(255)  NOT NULL,
  merchant       VARCHAR(120)  NOT NULL,
  category       VARCHAR(40)   NOT NULL,
  -- Sign convention: negative = debit (money out), positive = credit.
  amount         DECIMAL(12,2) NOT NULL,
  status         ENUM('posted','pending') NOT NULL DEFAULT 'posted',
  -- Running ledger balance after this entry posted.
  -- NULL while the transaction is still pending.
  balance_after  DECIMAL(12,2) NULL,
  PRIMARY KEY (id),
  KEY idx_txn_account_date (account_id, date DESC),
  KEY idx_txn_category (category),
  KEY idx_txn_transfer (transfer_id),
  CONSTRAINT fk_txn_account
    FOREIGN KEY (account_id) REFERENCES accounts (id),
  CONSTRAINT fk_txn_transfer
    FOREIGN KEY (transfer_id) REFERENCES transfers (id),
  CONSTRAINT ck_txn_posted_has_balance
    CHECK (status = 'pending' OR balance_after IS NOT NULL)
) ENGINE=InnoDB;

-- ------------------------------------------------------------
-- Derived view: available balance per account
-- (what the mock layer stores as `availableBalance`)
-- ------------------------------------------------------------
CREATE VIEW account_available_balances AS
SELECT
  a.id,
  a.ledger_balance,
  COALESCE(SUM(ABS(t.amount)), 0)                    AS pending_holds_total,
  a.ledger_balance - COALESCE(SUM(ABS(t.amount)), 0) AS available_balance
FROM accounts a
LEFT JOIN transactions t
  ON t.account_id = a.id
 AND t.status = 'pending'
 AND t.amount < 0
GROUP BY a.id, a.ledger_balance;

-- ------------------------------------------------------------
-- Transfer semantics (enforced in application code today,
-- by DB transaction when a real backend exists):
--
--   START TRANSACTION;
--     1. SELECT both accounts FOR UPDATE (row locks)
--     2. Validate: both active, same customer, amount <= available
--     3. INSERT INTO transfers (...)
--     4. UPDATE accounts SET ledger_balance = ledger_balance - :amt
--        WHERE id = :from;
--     5. UPDATE accounts SET ledger_balance = ledger_balance + :amt
--        WHERE id = :to;
--     6. INSERT the debit and credit rows into transactions
--   COMMIT;  -- or ROLLBACK on any failure: all-or-nothing
-- ------------------------------------------------------------

-- ------------------------------------------------------------
-- Minimal sample seed (the app generates a richer dataset in
-- src/data/seedData.js — this is just to make the DDL runnable)
-- ------------------------------------------------------------
INSERT INTO customers (id, name, email) VALUES
  ('cust-001', 'Jordan Lee', 'jordan.lee@example.com');

INSERT INTO accounts (id, customer_id, account_number, nickname, type, status, ledger_balance) VALUES
  ('acc-checking', 'cust-001', '4471820156', 'Primary Checking',  'checking', 'active', 4250.75),
  ('acc-savings',  'cust-001', '5583910442', 'High-Yield Savings','savings',  'active', 12800.00),
  ('acc-travel',   'cust-001', '5583910775', 'Travel Fund',       'savings',  'active', 1200.50),
  ('acc-legacy',   'cust-001', '3390004411', 'Legacy Checking',   'checking', 'frozen', 300.00);

INSERT INTO transfers (id, from_account_id, to_account_id, amount, note) VALUES
  ('xfer-seed-01', 'acc-checking', 'acc-savings', 500.00, 'Monthly savings');

INSERT INTO transactions (id, account_id, transfer_id, date, description, merchant, category, amount, status, balance_after) VALUES
  ('txn-0001', 'acc-checking', NULL,           NOW() - INTERVAL 3 DAY,  'Payroll deposit',                 'Acme Corp Payroll', 'Income',   2400.00, 'posted',  4750.75),
  ('txn-0002', 'acc-checking', 'xfer-seed-01', NOW() - INTERVAL 2 DAY,  'Transfer to High-Yield Savings',  'Internal transfer', 'Transfer', -500.00, 'posted',  4250.75),
  ('txn-0003', 'acc-savings',  'xfer-seed-01', NOW() - INTERVAL 2 DAY,  'Transfer from Primary Checking',  'Internal transfer', 'Transfer',  500.00, 'posted', 12800.00),
  ('txn-0004', 'acc-checking', NULL,           NOW() - INTERVAL 1 DAY,  'Pending — card authorization',    'The Local Bistro',  'Dining',    -84.20, 'pending',    NULL);
